### ISSUE TITLE
Update KitchenSink to use the "Trigger$" pattern in JSON

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/KitchenSink#105]
All pages that have button handlers should be changed to have the property names follow the  `XxxxTrigger$` pattern.

Discussion here: https://github.com/Starcounter/Guidelines/issues/12

**Comment by Mackiovello** [comment]
Fixed with https://github.com/StarcounterApps/KitchenSink/pull/108. Please close if satisfactory

Not sure about these buttons on the RedirectPage:

```html
<button value="{{model.ChooseFood$::click}}" onmousedown="this.value = 'Bread'">Bread</button>
```

I wouldn't consider this a trigger as we've defined it since it's value is something that will actually be used, compared to `this.value++` which only acts as a trigger. Would you say that it should be `ChooseFoodTrigger` instead?

Also, is it intentional that it shouldn't be possible to run tests locally? I get this error message on all the tests:

```
Test Name:	ButtonPage_RegularButton
Test FullName:	KitchenSink.Tests.Test.SectionNumber.ButtonPageTest(Chrome).ButtonPage_RegularButton
Test Source:	C:\Users\Erlend\Documents\apps\KitchenSink\test\KitchenSink.Tests\Test\SectionNumber\ButtonPageTest.cs : line 31
Test Outcome:	Failed
Test Duration:	0:00:00.0000001

Result Message:	
OneTimeSetUp: OpenQA.Selenium.WebDriverException : Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:4444
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)

```

**Comment by warpech** [comment]
I would not consider `RedirectPage` a trigger. 

Regarding the tests, have you checked the instructions? https://github.com/StarcounterApps/KitchenSink#run-the-test-from-visual-studio

**Comment by warpech** [comment]
I would not consider `ChooseFood$` a trigger.

**Comment by Mackiovello** [comment]
> Regarding the tests, have you checked the instructions? 

Hehe... That's usually good advice 😄 All tests pass. Merging and closing the issue
