### ISSUE TITLE
Use uniform batch scripts

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/KitchenSink#109]
Use uniform batch scripts as presented in https://starcounter.gitbooks.io/guidelines/content/batch-files.html

Discussion: https://github.com/Starcounter/Guidelines/issues/6

**Comment by KmaTTi89** [comment]
@warpech Done in https://github.com/StarcounterApps/KitchenSink/pull/110

**Comment by KmaTTi89** [comment]
Done in https://github.com/StarcounterApps/KitchenSink/pull/112
