### ISSUE TITLE
Add paper-input example to the TextPage with tests

### ISSUE THREAD

**Issue by alshakero** [StarcounterApps/KitchenSink#114]

**Comment by warpech** [comment]
Context: https://github.com/RemoteCloud/SystemLocationApp/issues/10#issuecomment-291100627

**Comment by warpech** [comment]
@PatrykSzwer could you please take this as your first task?

**Comment by warpech** [comment]
Details for this task:

In `TextPage.html` add two examples that usehttps://www.webcomponents.org/element/PolymerElements/paper-input and add a tests that verifies its correctness.

The examples should show:

1. paper-input sending value to the server after each keystroke
2. paper-input sending value to the server after blur

Hint: `paper-input` does not trigger standard DOM events like `input` nor `change`. To catch a change after each keystroke, listen to the event `value-changed`. To catch a change after blur, I don't know yet. Maybe `blur` event works?

`paper-input` must be installed using Bower, similarly how other elements in `wwwroot/sys` are installed.

**Comment by PatrykSzwer** [comment]
So officially, for the first time: fixed and closing!

**Comment by alshakero** [comment]
@PatrykSzwer awesome work! Glad to have you on board 🎉
