### ISSUE TITLE
Test.bat tests only in Chrome

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/KitchenSink#116]
`test.bat` is now configured to only run the tests in Chrome. Is this needed? I would prefer to test in the default set of browsers, as specified in test fixtures.

**Comment by warpech** [comment]
Should also be fixed in Launcher, Website (https://github.com/StarcounterApps/Website/pull/71) and https://github.com/Starcounter/Guidelines/blob/master/batch-files.md

**Comment by KmaTTi89** [comment]
@warpech 
If you prefer to test in the default set of browser there is `--params Browsers=Chrome` parameter that need to be deleted [here](https://github.com/StarcounterApps/KitchenSink/blob/master/test.bat#L18) then tests will be running on browser specified in code [here](https://github.com/StarcounterApps/KitchenSink/blob/master/test/KitchenSink.Tests/Test/BaseTest.cs#L32-L34)

**Comment by warpech** [comment]
Yes, this is what I meant. Can you please make a PR?

**Comment by KmaTTi89** [comment]
Done
