### ISSUE TITLE
Add a page that mixes the view-model and the local state

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/KitchenSink#135]
Some users need to keep local state of objects, for example:

- have an array of items
- present each item in a `dom-repeat`
- for each item have a local property that represents the mouse hover. 
  - That local property should be available to Polymer but not part of the view-model that is synced with the server

@alshakero could you pls prepare a page for that in KitchenSink?

**Comment by alshakero** [comment]
I think this is closable with https://github.com/StarcounterApps/KitchenSink/pull/136 now.

**Comment by warpech** [comment]
Closing. Thanks @alshakero!
