### ISSUE TITLE
Ungroup the test subfolders

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/KitchenSink#137]
In the tests folder https://github.com/StarcounterApps/KitchenSink/tree/1b8b41aea334bc491f6c1afbf62ce70b38c63421/test/KitchenSink.Tests/Test, there are subfolders that correspond to the NavPage menu groups that are no longer in place.

I suggest to flatten the tests folders, just alike the viewmodels folder has a flat file structure too.

**Comment by PatrykSzwer** [comment]
I actually have an opposite idea. Wouldn't be more clear if all viewmodels, views and tests were in subfolders that correspond with new navigation that was implemented here https://github.com/StarcounterApps/KitchenSink/pull/130? That could make moving trough the solution more intuitive and solution itself would be much cleaner. @warpech what do You think?

**Comment by warpech** [comment]
I would like to keep all examples in the same folder, because the navigation may change again in future.

After #137 we should apply the correct project structure though: #143

**Comment by bouguila** [comment]
closing as done.
