### ISSUE TITLE
Add table/select example

### ISSUE THREAD

**Issue by jwillmer** [StarcounterApps/KitchenSink#14]
Example of creating a table and selecting an item in the table.

Make a note in the example about the polymer bug: https://github.com/Polymer/polymer/issues/2497

**Comment by warpech** [comment]
Thanks but where did you add it? Perhaps you forgot to push/make a pull request

**Comment by miyconst** [comment]
I think @jwillmer meant, that we should add it to KitchenSink with note, that `onclick="++this.value;"` works only if the HTML node does not have child nodes.

**Comment by jwillmer** [comment]
Sorry, did too much in parallel yesterday. The title is misleading. @miyconst is right, it is a proposal.

**Comment by Mackiovello** [comment]
This is fixed with https://github.com/StarcounterApps/KitchenSink/pull/134
