### ISSUE TITLE
Navigating should scroll to top

### ISSUE THREAD

**Issue by alshakero** [StarcounterApps/KitchenSink#144]
I'm not sure if this should be in `PalindromDOM` instead. But to me, the current setting is very unintuitive.

Traditionally, when we navigate we expect a full page load and a fresh start from Y=0. 

To observe this issue, please scroll to the very bottom in KitchenSink and click a nav link. It will seem like nothing had happened.

**Comment by warpech** [comment]
This actually is bugging me since long time. The effect of morphing a page is not visible, when it happens outside the viewport.

That said, I don't think `PalindromDOM` should do anything special.

Maybe we can fix this with pure HTML right in KitchenSink? This entails to change links from `<a href="/KitchenSink/Breadcrumb">Breadcrumb</a>` to `<a href="/KitchenSink/Breadcrumb#top">Breadcrumb</a>`. 

> You can use href="#top" or the empty fragment href="#" to link to the top of the current page. This behavior is specified by HTML5. [source](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a)

If we hate to have `#top` in URLs, then another option is to use an `on-click` handler with JavaScript that scrolls to top.

@tomalec, @mmnosek, @miyconst, any other ideas?

**Comment by mmnosek** [comment]
> Traditionally, when we navigate we expect a full page load and a fresh start from Y=0.

Traditionally I agree, but we need to remember that Starcounter-based apps are not "traditional" so we should not force this behavior. It should be up to the developer. For me `#top`/`on-click` handler looks fine for this purpose.

**Comment by alshakero** [comment]
@mmnosek I'd suggest an opt-out mechanism for those who want to stay at the same Y after navigation. Something like `<a href='#' preserve-y>in-page-link</a>`.

I guess `<a />` links are very rarely used to change something on the same page without navigating. Buttons are usually used to change page contents in place. At least most the time.

**Comment by warpech** [comment]
Interesting perspective, @alshakero. 

> Traditionally I agree, but we need to remember that Starcounter-based apps are not "traditional" so we should not force this behavior. It should be up to the developer. For me #top/on-click handler looks fine for this purpose.

I was thinking the same, but actually you have to admit that our Palindrom is hijacking these "traditional" links and forcing the behavior of page-morph. @alshakero is right that scrolling to top is the "traditional" thing to do, actually.

----

This seems to be what [Turbolinks](https://github.com/turbolinks/turbolinks) is doing, and that library is also hijacking `<a href>` in the same domain to do page transitions.

Regarding scrolling, here's their behavior:

> If the visit’s location includes an anchor, Turbolinks will attempt to scroll to the anchored element. Otherwise, it will scroll to the top of the page.

Turbolinks is a [5-year old](https://twitter.com/dhh/status/251111584317972480) project, so I think they got few things right.

@tomalec WDYT?

**Comment by mmnosek** [comment]
> I was thinking the same, but actually you have to admit that our Palindrom is hijacking these "traditional" links and forcing the behavior of page-morph. @alshakero is right that scrolling to top is the "traditional" thing to do, actually.

I agree :)

> I guess <a /> links are very rarely used to change something on the same page without navigating. Buttons are usually used to change page contents in place. At least most the time.

This is true. Most of the time traditional approach is what the developer expect, so if we leave an easy way to achieve "not-traditional" results, I'm perfectly fine with it!

**Comment by warpech** [comment]
Ok, but then actually the implementation is to be done in `PalindromDOM`. @alshakero can this be added to Palindrom 3.0.0? Can you make an issue there?

I guess it is fine if we don't fix it ad hoc in KitchenSink.

**Comment by alshakero** [comment]
I'll reference the issue in the re-organization issue. We have 2-3 decision to make before knowing where to have this.

**Comment by tomalec** [comment]
I totally vote for 
> If the visit’s location includes an anchor, Turbolinks will attempt to scroll to the anchored element. Otherwise, it will scroll to the top of the page.

**Comment by warpech** [comment]
@alshakero can you please make an issue for this in Palindrom repo (to be fixed in PalindromDOM)? Then this issue can be closed as tracked elsewhere.

**Comment by alshakero** [comment]
Done

**Comment by alshakero** [comment]
Closing as tracked in https://github.com/Palindrom/Palindrom/issues/140
