### ISSUE TITLE
Add a note that VS 2017 is required

### ISSUE THREAD

**Issue by tomalec** [StarcounterApps/KitchenSink#146]
### Steps to reproduce
1. Clone develop,
2. Open solution in VS2015
3. Try to build

### Expected result
It should build.

### Actual result
It does not build

### Technical information
Visual Studio: Community 2015, 14.0.25431.01 Update 3
.NET: 4.7.02046

##### Involved apps' version

@a35a6f01ad81944efb0c94a5399928c2ce30ee34
 
##### Browsers affected
n/a
### Screenshot

Or maybe we should change our docs, and require VS 2017? //cc @Mackiovello

**Comment by Mackiovello** [comment]
> Or maybe we should change our docs, and require VS 2017? //cc @Mackiovello

Since we just require VS 2017 for some of our sample apps, I don't think we should create a blanket requirement.

Added a note for this repo in 	407d2bd. Closing as done

**Comment by warpech** [comment]
Two things related to https://github.com/StarcounterApps/KitchenSink/commit/407d2bdd615f74256416bff44e7941d27cd1a88b:

1. Don't you think it should be better added in `CONTRIBUTING.md`, where all the developer instructions are?
2. Some apps ("Products" at least) used to have similar information in CONTRIBUTING.md, but that was removed few months ago: https://github.com/StarcounterApps/Products/commit/23f6543fb361f7f7fc0ebfbdfefcc10d9c9531cc#diff-6a3371457528722a734f3c51d9238c13
3. The language is officially called "C# 7.0", sometimes "C# 7". Never "C#7".

**Comment by Mackiovello** [comment]
> Don't you think it should be better added in CONTRIBUTING.md, where all the developer instructions are?

In [other apps](https://github.com/starcounterapps/people) the requirements are in the README. The difference is that those are just for running the application while these instructions are for building. I'm considering moving everything to the README, including the instructions for building and running. The separation between the README and CONTRIBUTING feels borderline arbitrary.

> Some apps ("Products" at least) used to have similar information in CONTRIBUTING.md, but that was removed few months ago: StarcounterApps/Products@23f6543#diff-6a3371457528722a734f3c51d9238c13

That might have been a mistake. Although, since we require VS 2015 or 2017 for Starcounter, it's not too far-fetched that users of the apps have one of those versions installed. I think we should only put a note if it requires something that is not covered by the Starcounter system requirements, such as using C# 7. 

> The language is officially called "C# 7.0", sometimes "C# 7". Never "C#7".

Didn't know that. Will fix.

**Comment by warpech** [comment]
> That might have been a mistake. Although, since we require VS 2015 or 2017 for Starcounter, it's not too far-fetched that users of the apps have one of those versions installed. I think we should only put a note if it requires something that is not covered by the Starcounter system requirements, such as using C# 7.

That notes were added where many devs were till on VS 2013, where C# 6 was unavailable. Back then VS 2013 was officially supported target IDE by Starcounter. So the same story, just in the past.

---

I have one more comment regarding the sentence: 

> An alternative is to download [Microsoft.Net.Compilers](https://www.nuget.org/packages/Microsoft.Net.Compilers/) for Visual Studio 2015.

I don't think you "download" the compilers for VS 2015. You need to install it in the project, which alters the project. @joozek78, @ubbeK should the above sentence be rephrased?

**Comment by joozek78** [comment]
>> An alternative is to download Microsoft.Net.Compilers for Visual Studio 2015.
> I don't think you "download" the compilers for VS 2015. You need to install it in the project, which alters the project. @joozek78, @ubbeK should the above sentence be rephrased?

"An alternative is to install Microsoft.Net.Compilers in KitchenSink project using nuget (Install-Package Microsoft.Net.Compilers. That will make VS use the C# compiler provided in the package instead of the one provided by VS itself."

**Comment by warpech** [comment]
Thank you @joozek78. I have added the explanation, slightly changed.

**Comment by warpech** [comment]
Thanks @Mackiovello too! Closing as done
