### ISSUE TITLE
Remove Bind syntax in json-by-example

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterApps/KitchenSink#152]
As I understand it, this syntax is not a best practice anymore:

[IntegerPage](https://github.com/StarcounterApps/KitchenSink/blob/fad83975ec3b4ebf6201458ea228547e6756d507/src/KitchenSink/IntegerPage.json) 
```json
"$AgeReaction": { "Bind": "CalculatedAgeReaction" }
```

We use it in a [couple of places](https://github.com/StarcounterApps/KitchenSink/search?utf8=%E2%9C%93&q=%22Bind%22%3A&type=). Instead, bindings like these should be made in the [code-behind](https://docs.starcounter.io/guides/typed-json/json-data-bindings/#binding-to-properties-with-different-names).

**Comment by warpech** [comment]
@Mihaiii could you please take this?

**Comment by Mihaiii** [comment]
Closing as done.
