### ISSUE TITLE
A lot of tests are failing in 2.3.1.7356

### ISSUE THREAD

**Issue by un-tone** [StarcounterApps/KitchenSink#178]
More info in TeamCity: https://teamcity.starcounter.org/viewType.html?buildTypeId=Apps_KitchenSink_Develop&branch_Apps_KitchenSink=develop

**Comment by warpech** [comment]
@PatrykSzwer you were looking into this. Any conclusions?

**Comment by PatrykSzwer** [comment]
I've posted details here: https://github.com/StarcounterApps/KitchenSink/pull/174#issuecomment-333511015
Don't know the solution yet.

**Comment by PatrykSzwer** [comment]
Restarting agent fixed this problem. Closing. Feel free to reopen if this problem going to came up again.
