### ISSUE TITLE
Markdown return error "Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by aloscha** [StarcounterApps/KitchenSink#26]
After run Kitchensink, please do steps:
1. Start Kitchensink with KitchenSink/Markdown
2. Go to Password tab, by clicking in menu

Now we have error with stacktrace:
`marked.js:138 Uncaught TypeError: Cannot read property 'replace' of undefined
Please report this to https://github.com/chjj/marked.Lexer.lex @ marked.js:138Lexer.lex @ marked.js:129marked @ marked.js:1218Polymer.parseText @ juicy-markdown.html:79Polymer.valueChanged @ juicy-markdown.html:76Polymer.Base.extend._observerEffect @ polymer.html:1563Polymer.Bind._modelApi._effectEffects @ polymer.html:1402Polymer.Bind._modelApi._propertySetter @ polymer.html:1386Polymer.Bind._modelApi.__setProperty @ polymer.html:1395Polymer.Base._addFeature._applyEffectValue @ polymer.html:1894Polymer.Base.extend._annotationEffect @ polymer.html:1546Polymer.Bind._modelApi._effectEffects @ polymer.html:1402Polymer.Bind._modelApi._propertySetter @ polymer.html:1386setter @ polymer.html:1465JuicyHTMLPrototype.attachModel @ juicy-html.html:124ImportedTemplatePrototype.attachModel @ imported-template.html:139Object.defineProperty.set @ juicy-html.html:18StarcounterIncludePrototype.partialChanged @ starcounter-include.html:87Object.defineProperty.set @ starcounter-include.html:45Polymer.Bind._modelApi.__setProperty @ polymer.html:1397Polymer.Base._addFeature._applyEffectValue @ polymer.html:1894Polymer.Base.extend._annotationEffect @ polymer.html:1546Polymer.Base._addFeature._annotationPathEffect @ polymer.html:2154Polymer.Base._addFeature._pathEffector @ polymer.html:2144Polymer.Base._addFeature._notifyPath @ polymer.html:2045_notifyNodes @ imported-template.html:149ImportedTemplatePrototype._notifyPath @ imported-template.html:179StarcounterIncludePrototype._notifyPath @ starcounter-include.html:99Polymer.Base._addFeature._annotationPathEffect @ polymer.html:2159Polymer.Base._addFeature._pathEffector @ polymer.html:2144Polymer.Base._addFeature._notifyPath @ polymer.html:2045_notifyNodes @ imported-template.html:149ImportedTemplatePrototype._notifyPath @ imported-template.html:179Polymer.Base._addFeature._annotationPathEffect @ polymer.html:2159Polymer.Base._addFeature._pathEffector @ polymer.html:2144Polymer.Base._addFeature._notifyPath @ polymer.html:2045Polymer.Base._addFeature.set @ polymer.html:2104Polymer.notifyTemplateDomBind @ puppet-client.html:356Polymer.propagateDomBind @ puppet-client.html:235Polymer.applyJSONPatch @ puppet-client.html:289Puppet.validateAndApplySequence @ puppet.js:582applyOT @ json-patch-ot-agent.js:72JSONPatchQueue.receive @ json-patch-queue.js:67Puppet.handleRemoteChange @ puppet.js:636(anonymous function) @ puppet.js:247req.onload @ puppet.js:288`

**Comment by warpech** [comment]
@tomalec could you please take a look. After this is fixed, please add a Selenium test page for it.

**Comment by tomalec** [comment]
Issue is fixed, only test is left.

**Comment by warpech** [comment]
@KmaTTi89 could you please add a test for the Markdown page?

**Comment by KmaTTi89** [comment]
I can try

**Comment by warpech** [comment]
Closing as done
