### ISSUE TITLE
Clean up the usage of headings

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/KitchenSink#27]
Currently, KitchenSink pages use headings in a very inconsistent manner.

Every page should have a `h1` heading with a BEM Block class modifying its font size. Every consecutive heading should be `h2`, `h3`, etc... 

Font-size modifications should be done in BEM. I propose the following scheme:

``` html
<h1 class="kitchensink-heading-1">
<h2 class="kitchensink-heading-2">
<!-- etc... -->
```

**Comment by PatrykSzwer** [comment]
Changes merged in #130. Closing.
