### ISSUE TITLE
KitchenSink + Luncher fails on Selenium tests

### ISSUE THREAD

**Issue by aloscha** [StarcounterApps/KitchenSink#46]
I run Selenium test on KitchenSink + luncher and 95% tests fail. Is our test must be also working with luncher.

>  I guess it is because the XPath selectors don't match.
> To make the tests run both in Launcher and without it, we need to add discrete IDs to every tested >HTML element.
> 
> Maybe we could use some short attributes like data-testid="kitchensink-123". Then it is enough to use a >CSS attribute selector [data-testid="kitchensink-123"] in the test. I would like that.

**Comment by joozek78** [comment]
I'd use normal ids instead. They can (and should) be used in production code.

**Comment by aloscha** [comment]
@joozek78 please remember that there could be many applications using id with the same name as yours, when we will use joining apps. So I think better one is to using `data-testid="kitchensink-123`

**Comment by joozek78** [comment]
Well, to avoid conflict we use id prefix "kitchensink-", but what I meant
is not to use 'data-testid' field, but just 'id'

**Comment by aloscha** [comment]
cc @warpech

**Comment by warpech** [comment]
> Well, to avoid conflict we use id prefix "kitchensink-", but what I meant
is not to use 'data-testid' field, but just 'id'

Ok, it's fine for me

**Comment by warpech** [comment]
Closing as we are no longer testing KitchenSink with Launcher
