### ISSUE TITLE
Could we keep the KitchenSink repository clean and tidy?

### ISSUE THREAD

**Issue by miyconst** [StarcounterApps/KitchenSink#55]
I just have checked out the latest KitchenSink and the `Pattern_for_input_validation` branch and was sad to see that we don't follow our own [guidelines](https://starcounter.gitbooks.io/guidelines/content/).

We cannot ask for side developers to provide well formed pull requests if we do not follow that in our own commits.

Also we can't tell our customers that this is our guidelines and practices if the first repository they read does not follow it.

cc @warpech, @joozek78, @aloscha, @ubbeK

**Comment by warpech** [comment]
I totally agree that we must follow our own Guidelines.

On the other hand, I think we cannot ask our customers to change their coding style. The feedback that I get from every C# developer is that they don't like our non-default coding style.

Maybe we should revote changing the Guidelines?

**Comment by warpech** [comment]
After so many fights about this, I believe we should just adopt https://msdn.microsoft.com/en-us/library/ff926074.aspx. We win familiarity in the eyes of C# developers.

Anyone disagree?

**Comment by aloscha** [comment]
@warpech I think evety C# developer says apout parenthesis position (new line or the same line)

**Comment by warpech** [comment]
Btw. these are the most popular conventions according to GitHub: http://sideeffect.kr/popularconvention/#c#

**Comment by ubbeK** [comment]
I always liked the brackets on new line, keep them on the same line feels like something Java-developers use.

**Comment by joozek78** [comment]
I think that whatever convention is good, as long as we adhere. Changing conventions can prove cumbersome (it will cause some confusion for our existing customers, do we change it gradually or make tons of changes across all repositories?)

**Comment by miyconst** [comment]
>Maybe we should revote changing the Guidelines?

Agree.

>Anyone disagree?

Nope :).

>I always liked the brackets on new line, keep them on the same line feels like something Java-developers use.

Me too. When I joined Starcounter, the "java-style" was the default coding format, and everyone in the team seemed to like it. I am a flexible person, and did not want to go against entire team, so I just adopted the style.

Now it looks like more and more people like the default Microsoft format, so do I.

Our customers do not have to follow our guides, same we should not ask them to do so, but we should be able to provide description of what we use in the company, and ask to follow the guides those who rise pull request.

P.S. With the guidelines I am pointing to all the guides, no only the position of `{`.

**Comment by warpech** [comment]
Just checked codebase of three of our customers and they all use Microsoft/default convention. @jwillmer is an exception, he seems to have switched to our convention very recently. I will reach out to him on Skype.

@miyconst are the Visual Studio defaults the same for C# as the Microsoft's convention?

**Comment by miyconst** [comment]
>@miyconst are the Visual Studio defaults the same for C# as the Microsoft's convention?

Yes. To use our current style we have to make adjustments in the settings. @jwillmer is more like forced to switch.

**Comment by warpech** [comment]
> I think that whatever convention is good, as long as we adhere. Changing conventions can prove cumbersome (it will cause some confusion for our existing customers, do we change it gradually or make tons of changes across all repositories?)

We are a platform vendor, not just a software house. So we must take into account that other people will judge our code by their standards.

I am not a well seasoned C# devleloper, but I consider myself a experienced JS dev. If I so C# formatting in JS, I would loose my senses :) So I can imagine this works the other way, too.

---

@miyconst I think we can call it decided then! Will you change the https://github.com/StarcounterPrefabs/Guidelines? Then we can gradually reformat existing apps.

**Comment by joozek78** [comment]
I just think that it's our convention and other people / companies don't
have to use it. IMO it doesn't make our code any harder to read or use,
it's just that our examples are a little bit weird to C# people. If you
guys think that it imposes itself on our customers, then I agree we should
consider changing it. I just don't think that it does (but I haven't worked
with them directly)

**Comment by aloscha** [comment]
@warpech maybe we could use some style plugin for all people coding with SC like AStyle?

**Comment by miyconst** [comment]
>@miyconst I think we can call it decided then! Will you change the https://github.com/StarcounterPrefabs/Guidelines? Then we can gradually reformat existing apps.

As soon as other members agree - I agree :).

For the code updating, I propose the following:

- The first person to make a change in a file or an app (if the app is small enough) has to apply new format.
- The code formatting should be done as a separated commit, and should not include any other changes except the code formatting.
- It's not allowed to use new format while keeping the rest of the file with old format.
- It is allowed to make changes in an old formatted file while keeping the old format, if this is really required.

**Comment by ubbeK** [comment]
I agree

**Comment by miyconst** [comment]
The [guidelines](https://starcounter.gitbooks.io/guidelines/content/coding_style/csharp_code_formatting.html) have been updated.

**Comment by dan31** [comment]
Guys, in my opinion, the way how Microsoft provides defaults tend to make code not fit onto a single screen much more frequent than with our recently preferred style, which is very unfortunate. New lines put on every sneeze makes it too spread on the screen. Starcounter promotes supersimple development and declarative style, which I think doesn't live well at all with this "cold butter" style of parenthesis.

On the other hand, what you came up as an origin sounds quite aligned to our product strategy. Starcounter stops to be a platform of a single host (.NET). Node.js, Python and other goodness is yet to come. Each of these platforms has a sort of "dictated" standard, motivated by the main platform owners. In .NET, it is Microsoft which promotes its style all the way down, starting from VS defaults. In Node.js these are guys maintaining node.js. And so on. Yes, it is admissible that it is strange to newcomers to see a code which isn't aligned to their IDE defaults.

Personally I feel terrified by such a "smash on a screen" parenthesis style. It goes away from a concise declarative minimalist code and it smashes the focus away to empty lines. The same opinion @Starcounter-Jack shares. However, I cannot put our strong opinion against the users of the platform. Of course, I would rather see our partners adopting the minimalist style with less new lines because it emphasizes on the value of business logic and declarative style over the value of lines-of-code count. Emphasising on a value of clean, concise code is why we've chosen less-empty-lines style long time ago. We explain it to them, they agree and adopt it - that is ideal picture. Apparently, from your comments I see that this way doesn't work that well, correct? So, if there is really strong, logical, facts-mostly reason to fall back to VS default, then it has to be a VS-default.

I basically rephrase @joozek78 there. If our current style makes more harm than goodness on a way of adopting new users, then we should address it.

> The feedback that I get from every C# developer is that they don't like our non-default coding style.

@warpech can you elaborate what exactly they dislike? How do they say that?

**Comment by miyconst** [comment]
@dan31 as what I can see from many part of our code is that we **do not** save the empty lines. This is what I mean:

```cs
if (i > 0) {

    i++;
}
```

This is not shorter than:

```cs
if (i > 0)
{
    i++;
}
```

>It goes away from a concise declarative minimalist code and it smashes the focus away to empty lines.

So, it does not go, it already went like this, especially in the `Starcounter.Level1` repository.

>The feedback that I get from every C# developer is that they don't like our non-default coding style.

I can also add some feedback from newcomers, our customers and random guys which I asked to take a look at Starcounter.

- Why do you use Microsoft products and go against their coding format?
- Ah! I didn't even know I can change the default new lines style in Visual Studio.
- Oh, no, I can't change my Visual Studio settings, because I have other projects I have to maintain.
- Well, this is just awkward, try to force any senior JavaScript developer to use C# coding style and I will see how it goes.
- You see! This is not convenient, even some guys of your team does not use your coding style.
- You blame Java for being very heavy, but following it's coding style.

>Personally I feel terrified by such a "smash on a screen" parenthesis style.

There is amount of code you can see on screen, and amount of code you can interpret per screen. For me it feels more easy to explain such code not only because it is easier to read, but also because while reading empty lines people have time to interpret the code lines and don't get fed with a new line of code immediately and then fail with BrainOverflowException.

As I already said, I am ready to use any format we have in the company, but I will ask the same from every team member as well.

**Comment by joozek78** [comment]
Did the change went through already? I saw that it's already updated in [Guidelines](https://starcounter.gitbooks.io/guidelines/content/coding_style/csharp_code_formatting.html), but at the same time I thought didn't agreed yet.

**Comment by miyconst** [comment]
Yes, it has happened that I updated the Guidelines right before @dan31's comment.

It is easy to revert the update, but the final decision is up to @dan31 and @warpech.

**Comment by joozek78** [comment]
do the Guidelines pertain to Starcounter code? I mean the C# code in Starcounter repository? Does this update (coding style) concern Starcounter repository?

**Comment by miyconst** [comment]
As much as I would want, I can't ask the Starcounter.Level1 guys to following the same guidelines we use for apps.

So, the guidelines apply to the Starcounter apps, and others may or may not follow it.

**Comment by Mackiovello** [comment]
Archiving
