### ISSUE TITLE
Type cannot be changed in breadcrumbs in polyfilled browsers

### ISSUE THREAD

**Issue by tomalec** [StarcounterApps/KitchenSink#77]
### Steps to reproduce

1. Run KitchenSink
2. Open [/KitchenSink/Breadcrumb](http://localhost:8080/KitchenSink/Breadcrumb)
3. Click on "Diary" under "Breadcrumb with navigation"
4. Click on "Meat"

### Expected result
"Diary" should be changed to "Meat"

### Actual result
...it's not

### Technical information

No trace in the console

##### Involved apps' version

 - StarcounterSamples/KitchenSink@4f6309355854cf298a1decba14c5ea298dae35b5 (current HEAD of develop)
 
##### Browsers affected

- [ ] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [?] Safari 8
- [x] IE 11

### Screenshot
![breadcrumbs](https://cloud.githubusercontent.com/assets/17435/20060728/cd96c696-a4fc-11e6-994f-2722fc74d40b.gif)

**Comment by warpech** [comment]
@PatrykSzwer could you pls check if this is still reproducible?

**Comment by PatrykSzwer** [comment]
Hey,

I checked that issue on current HEAD of develop: https://github.com/StarcounterApps/KitchenSink/commit/3a9efaafd46666f374ba088f769677ed806a86bf

and I think it's not reproducible anymore. Navigation works as It's expected to.
![image](https://cloud.githubusercontent.com/assets/25042256/25434628/4cf01bc0-2a8d-11e7-9308-7394e9f3f9cd.png)


**after click:**

![image](https://cloud.githubusercontent.com/assets/25042256/25434654/65faa892-2a8d-11e7-968b-e37abdc7f725.png)

**Comment by PatrykSzwer** [comment]
I've checked this on latest Firefox (v. 53.0) and it's still reproducible.

**Comment by PatrykSzwer** [comment]
Fix on PR #124

**Comment by PatrykSzwer** [comment]
Fixed on PR #124, closing.
