### ISSUE TITLE
Add a flash message example

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/KitchenSink#84]
Add a server-side driven flash-message example, as implemented at the commit linked below.

**Comment by miyconst** [comment]
I think @Joltrix can take this issue.

There should be two examples:

1. Hide alert message from server side.
2. Hide alert message from client side.

**Comment by warpech** [comment]
Both examples are now implemented in the repo linked above, they just need to be extracted and (maybe) generalised.

**Comment by Joltrix** [comment]
Implemented in this [PR](https://github.com/StarcounterSamples/KitchenSink/pull/91)
