### ISSUE TITLE
Improve the look of pagination

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/KitchenSink#90]
After #85 is done, copy the nice look of pagination from the People app (https://github.com/StarcounterSamples/People/issues/68)

**Comment by warpech** [comment]
@PatrykSzwer could you please take this?

**Comment by PatrykSzwer** [comment]
I'm on it.

**Comment by PatrykSzwer** [comment]
Created PR #123

**Comment by PatrykSzwer** [comment]
Fixed in #123, closing.
