### ISSUE TITLE
Adapt view to Declarative Shadow DOM

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterApps/KitchenSink#97]
According to https://github.com/Starcounter/RebelsLounge/issues/59

Follow the guidelines in the following three posts to adapt the views to use Declarative Shadow DOM:

* [Layout compositions for HTML partials](https://starcounter.io/layout-compositions-html-partials/)
* [How to Apply New Shadow DOM Layouts to Existing HTML Templates](https://starcounter.io/making-apps-blendable/)
* [HTML View Guidelines](https://docs.starcounter.io/guides/puppet-web-apps/html-view-guidelines/)

**Comment by warpech** [comment]
@PatrykSzwer could you pls take this? 

You will find reference implementation in other sample apps by going to https://github.com/Starcounter/RebelsLounge/issues/59 and scrolling down. There is a list of sibling issues that are already solved in other apps. Each issue has a link to a PR.

**Comment by PatrykSzwer** [comment]
Sure, I'm on it.

**Comment by PatrykSzwer** [comment]
I've made first changes on AutocompletePage (https://github.com/StarcounterApps/KitchenSink/commit/42d25fe8910c5568440f015944e8a1b861ce1eec). Please if You can, make sure it those changes are okey and meanwhile I'll adapt rest of the views.

**Comment by warpech** [comment]
@PatrykSzwer can you pls make the PR for the purpose of reviewing. Just write in it that it is not mergable yet.

@Mackiovello could you pls review the PR?

**Comment by PatrykSzwer** [comment]
I've done +- half of files. @warpech , @Mackiovello , could You review current changes and look if everything is ok for now?

**Comment by Mackiovello** [comment]
I just have a question first, it seems like you are not using `declarative-shadow-dom` when there is no layout except for the ordering of the elements. Is this a best practice?

**Comment by PatrykSzwer** [comment]
You're right. It's not. I'll add that even if unnecessary in case of future changes.

**Comment by Mackiovello** [comment]
> You're right. It's not. I'll add that even if unnecessary in case of future changes.

I think we misunderstood each other here. In order to make it possible to easily modify the layout in the future, I believe that the elements should be added to the `declarative-shadow-dom` as well, even if there's no specific layout right now.

**Comment by tomalec** [comment]
First of all, I'd keep it consistent with regular element shadow DOM: If there is shadow root, add slot elements, otherwise nothing is distributed (we will prevent that for merged views in starcounter-include, by adding default slot); if there is not shadow root, there is no need for slots.

The the question "Should we always attach Shaow DOM, even if it's no-op?", the answer is related to our approach to implicit slot names, and implicit shadow dom in general https://github.com/Starcounter/RebelsLounge/issues/107 I would say we shouldn't add it if it's not needed and makes no change. 

To be "super easy", collapse the boilerplate and make Starcounter app pure juice in as few lines as possible.

**Comment by warpech** [comment]
I was saying the opposite in the beginning but I see @tomalec has strong opinion here and a good point. Just like in programming languages, you don't have to declare things you are not using.

However, our definitive documentation on blending (https://docs.starcounter.io/guides/web-apps/html-view-guidelines/) does not cover conditions when to apply it. It only gives simple guidelines:

1. should you always define views as partials (yes)
2. should you always separate presentation from content (yes)
3. should you always give slot names to you content (yes)
4. should you distribute slots in Shadow DOM (yes)

Maybe we should add it at the bottom of the page that if your default presentation equals the default rendering of the content, then you don't have to provide `declarative-shadow-dom` for it?

**Comment by tomalec** [comment]
I think it's deffinitely forth mentioning. We could add a metaphor to regular CSS.
You should keep styling in CSS files or blocks to separate the concerns, but if you don't have/use styles at all, you simple do not attach empty file nor empty `<style>`.

**Comment by warpech** [comment]
@Mackiovello can you pls add that?

**Comment by Mackiovello** [comment]
Fixed in 	https://github.com/Starcounter/Docs/commit/76b7129c23e0a009dc80d64cd7a01c62d5c68052

**Comment by PatrykSzwer** [comment]
Adaptation is complete (PR #125). Closing.
